# Site settings
title: boi - build for elegance
email: zjp0432@163.com
description: "前端工程化一站式解决方案"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boijs.github.io" # the base hostname & protocol for your site
github_username:  zhoujunpeng
github_team: boijs

# Build settings
markdown: kramdown
Exclude: ['src','boi-conf.js','deploy.js']

sass:
    sass_dir: _sass
    style: compressed
